'use client';

import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { KPITile } from "@/components/shared/kpi-tile";
import { ModuleDataTable } from "@/components/shared/module-data-table";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Tooltip } from "recharts";
import type { ChartConfig } from "@/components/ui/chart";

const roiKpis = [
    { title: "AI-Driven Cost Savings", value: "R1.2M", unit: "MTD", trend: "up" as const, trendValue: "vs last month", isAI: true },
    { title: "Operational Uplift", value: "+7.8%", unit: "Tonnes", trend: "up" as const, trendValue: "vs baseline", isAI: true },
    { title: "Safety Incident Reduction", value: "-22%", unit: "", trend: "down" as const, trendValue: "TRIFR vs baseline", isAI: true },
    { title: "ESG Compliance Score", value: "92", unit: "/100", trend: "up" as const, trendValue: "+5 pts", isAI: true },
];

const costSavingsData = [
  { name: 'Fuel Efficiency', savings: 450000, fill: "var(--color-chart-1)" },
  { name: 'Maintenance', savings: 320000, fill: "var(--color-chart-2)" },
  { name: 'Safety Incidents', savings: 280000, fill: "var(--color-chart-3)" },
  { name: 'Compliance Fines', savings: 150000, fill: "var(--color-chart-4)" },
];

const costSavingsChartConfig = {
  savings: { label: 'Savings (ZAR)' },
} satisfies ChartConfig;

const upliftData = [
    { area: 'Production Tonnes', baseline: '1.8M', current: '1.94M', uplift: '+7.8%' },
    { area: 'Haul Cycle Time', baseline: '38.1 min', current: '34.2 min', uplift: '-10.2%' },
    { area: 'Payload Efficiency', baseline: '96.5%', current: '98.2%', uplift: '+1.7%' },
    { area: 'Plant Throughput', baseline: '810 t/h', current: '850 t/h', uplift: '+4.9%' },
];

const upliftColumns = [
    { accessorKey: 'area', header: 'Operational Area' },
    { accessorKey: 'baseline', header: 'Baseline' },
    { accessorKey: 'current', header: 'Current (with Smart Hub)' },
    { accessorKey: 'uplift', header: 'Uplift' },
];

export default function SmartROIPage() {
  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-3xl font-headline font-semibold text-primary">Smart ROI Dashboard</h1>
        <p className="text-muted-foreground">Quantifying the value and return on investment of the Smart Mining Hub.</p>
      </header>

       <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
         {roiKpis.map((kpi, index) => (
            <KPITile
                key={index}
                title={kpi.title}
                value={kpi.value}
                unit={kpi.unit}
                trend={kpi.trend}
                trendValue={kpi.trendValue}
            />
         ))}
       </div>

      <Card>
        <CardHeader>
          <CardTitle>AI-Driven Cost Savings (MTD)</CardTitle>
          <CardDescription>Breakdown of estimated cost savings generated by AI-powered optimizations.</CardDescription>
        </CardHeader>
        <CardContent>
            <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={costSavingsData} layout="vertical" margin={{ left: 20, right: 20 }}>
                        <XAxis type="number" dataKey="savings" hide />
                        <YAxis dataKey="name" type="category" width={120} tickLine={false} axisLine={false} tick={{fontSize: 12, fill: 'hsl(var(--muted-foreground))'}} />
                        <Tooltip cursor={{ fill: 'hsl(var(--secondary))' }} contentStyle={{backgroundColor: 'hsl(var(--background))', border: '1px solid hsl(var(--border))'}} formatter={(value) => `R${Number(value).toLocaleString()}`} />
                        <Bar dataKey="savings" radius={[0, 4, 4, 0]} />
                    </BarChart>
                </ResponsiveContainer>
            </div>
        </CardContent>
      </Card>
      
      <ModuleDataTable
        title="Operational Uplift Analysis"
        description="Comparison of key performance indicators before and after Smart Hub implementation."
        columns={upliftColumns}
        data={upliftData}
      />
    </div>
  );
}
