
import { z } from 'zod';

export const NormalizedEventSchema = z.object({
  id: z.string().optional(), // Generated by firestore if missing
  tenantId: z.string(),
  siteId: z.string(),
  sourceType: z.enum(['device', 'integration', 'manual', 'api']),
  sourceId: z.string(),
  eventType: z.enum([
    'locationPing', 'alarm', 'kpiTick', 'formSubmit', 'incident', 'shift', 
    'trip', 'plantSensor', 'dustReading', 'airQuality', 'weatherUpdate',
    'maintenanceAlert', 'fuelLevel', 'collision', 'fatigueAlert', 'blastNotification'
  ]),
  ts: z.string().or(z.date()), // Flexible input, stored as ISO string or timestamp
  receivedAt: z.string().or(z.date()),
  subjectType: z.enum(['person', 'asset', 'device', 'site', 'zone']),
  subjectId: z.string(),
  severity: z.enum(['info', 'low', 'med', 'high', 'critical']),
  data: z.record(z.any()), // Structured data
  raw: z.record(z.any()).optional(),
  metadata: z.object({
    processedBy: z.string().optional(),
    validationStatus: z.enum(['valid', 'warning', 'invalid']).optional(),
    apiSource: z.string().optional(),
  }).optional(),
});

export type NormalizedEvent = z.infer<typeof NormalizedEventSchema>;

export const IngestionResponseSchema = z.object({
  success: z.boolean(),
  eventId: z.string().optional(),
  error: z.string().optional(),
  validationErrors: z.array(z.any()).optional(),
});
